spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                jdbc:
                    time_zone: Europe/Athens
        show-sql: true
    sql:
        init:
            mode: always

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
    api-docs:
        path: /api-docs

logging:
    level:
        root: DEBUG
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
            springframework:
                core:
                    env:
                        PropertySourcesPropertyResolver: TRACE
